spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            # REST CLIENT -> http://localHost:7070/api/patient
            # API GATEWAY -> http://patient-service:7001/patient
            - id: patient-service
              uri: http://patient-service:7001
              predicates:
                - Path=/api/patient/**
              filters:
                - StripPrefix=1
server:
  port: 7070
